Remove unnecessary borrow
Clippy emits various errors of form:

  error: this expression borrows a value the compiler would
  automatically borrow

As suggested, remove the unnecessary borrow.

FTR, this error shows up because of a clippy update (I believe).